apiVersion: v1
kind: Service

metadata:
  name: ride-fare-api
  labels:
    app: ride-fare-api      # <-- Add this

spec:
  type: {{ .Values.service.type }}

  selector:
    app: ride-fare-api

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP

      